### ISSUE TITLE
 CUDA out of memory issue

### ISSUE THREAD

**Issue by mshooter** [eladrich/latent-nerf#27]
Hi, I keep getting Cuda out of memory... 
Which parameters should I change for this?

**Comment by sq2001** [comment]
│   282 │                                                                                          │
│   283 │   def _maybe_opt_step(self, optimizer, optimizer_state, *args, **kwargs):                │
│   284 │   │   retval = None                                                                      │
│ ❱ 285 │   │   if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):    │
│   286 │   │   │   retval = optimizer.step(*args, **kwargs)                                       │
│   287 │   │   return retval                                                                      │
│   288                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: an illegal memory access was encountered

I solved this problem by:
1)  adding 
import os 
os.environ["CUDA_VISIBLE_DEVICES"] = '1'
in the first line of train_nerf.py
2) and in  trainer.py ,     def init_diffusion(self) -> StableDiffusion:

diffusion_model = StableDiffusion(self.device, model_name=self.cfg.guide.diffusion_name,
                                  concept_name=self.cfg.guide.concept_name,
                                  latent_mode=self.nerf.latent_mode)_**.to(self.device)**_

**Comment by flow-specter** [comment]
I have the same issue...

**Comment by qsong2001** [comment]
> 
if you met this issue:
**RuntimeError: CUDA error: an illegal memory access was encountered**

You can simply  try to re-run the training script repeatedly (like 4,5 times) .  It worked for me.

**Comment by SzaremehrjardiMT** [comment]
Same issue on 4GB RAM.
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 4.00 GiB total capacity; 3.38 GiB already allocated; 0 bytes free; 3.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
I tried different solutions such as reducing batch size, using torch.no_grad() for Inference and loading models in float16 precision instead of the default float32 precision; But none of them worked for me.

What is the minimum hardware requirements?
